spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.101.33.86:3306/mybatisplus?serverTimezone=UTC&useSSL=false&rewriteBatchedStatements=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: 1qazxsw2
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.zhoull.mybatisplus.entity
  global-config:
    db-config:
      id-type: auto
    banner: false
